### ISSUE TITLE
Sequence import API workflow is incorrect

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-web#104]
/api/v1/sequence/import

Currently requires mapillary sequence token on first request. This is incorrect.

Workflow should be:

* create sequence request (no mapillary info, just name, desc, tags and transport type) (POST /api/v1/sequence/import
)
* draft sequence create in MTPW, API responds with sequence id (but not visible in UI)
* update sequence record request (with mapillary token and key) (PUT /api/v1/sequence/import/SEQUENCEID)

We do not need two seperate endpoints like we do now

/mapillary/token/verify should be completely removed

This is to support MTPDU workflow

https://guides.trekview.org/mtp-desktop-uploader/developer-docs/integrations/map-the-paths-web
https://guides.trekview.org/mtp-desktop-uploader/developer-docs/integrations/mapillary

**Comment by good-lancer** [comment]
That is old version.
We can do it on #124
