### ISSUE TITLE
When user imports sequence from MTP Uploader (via API) must use Uploader Client ID and Secret

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-web#109]
In the desktop app user authenticates with Mapillary using the MTP Uploader Mapillary Oauth app.

In the web app user authenticates with Mapillary using the MTP Web mapillary oauth app to import sequence.

The MTP Web mapillary oauth app therefore will not have granted desktop user permission to use their account -- When they submit sequence key and user token, the MTP Web does not have correct token (the user has not granted MTPW permission in this case, they granted the desktop uploader).

In fact the API rejects due to invalid token.

To fix...

during create we should add source field on API

```
curl --location --request POST 'https://mtp.trekview.org/api/v1/sequence/create' \
--form 'name=<name>' \
--form 'description=<description>' \
--form 'transport_type=<transport_type>' \
--form 'tag=<tags>
--form 'source=mtpdu`
```

Therefore whenever sequence added via API put record

```
curl --location --request PUT 'https://mtp.trekview.org/api/v1/sequence/import/jjff8djf-jkld87-kls889' \
--data-raw '{
    "mapillary_sequence_key": "jf98fhhs76gggehfjs8",
    "mapillary_user_token": "8877fhsjjsggdnns0",
}'
``` 

And source = mtpdu

Then we use map the path desktop app mapillary oauth data.

This is stored in heroku

```
MTP_DESKTOP_UPLOADER_CLIENT_ID
MTP_DESKTOP_UPLOADER_CLIENT_SECRET
```

This is for API import ONLY. UI method of import should remain unchanged

**Comment by good-lancer** [comment]
#124
