### ISSUE TITLE
Mobile view should adjust map / list

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-web#116]
If sidebar clicked, the sidebar should force the map or list of cards to the right. Currently sidebar overlays on map. This causes some problems with viewing, as shown below:

![ba5041cb-0b06-43fa-b11f-4a64883d84e7](https://user-images.githubusercontent.com/1296409/93705587-d804b800-fb1e-11ea-9fe0-92fb186fcb6a.png)
![dfa26448-c066-48b2-8a93-e2f9b627caba](https://user-images.githubusercontent.com/1296409/93705589-d9ce7b80-fb1e-11ea-875a-b269917213b8.png)

**Comment by himynamesdave** [comment]
@good-lancer default should be sidebar opened on all views.

If user hides sidebar on one page, that then persists until the reopen it.

**Comment by good-lancer** [comment]
modified
