### ISSUE TITLE
Remove mapillary user token from /sequence/import/ endpoint

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-web#124]
/sequence/import/<MTP_SEQUENCE_UNIQUE_ID>

Token exchange is now handled by dedicated endpoints for security

https://guides.trekview.org/mtp-web/developer-docs/api#mtpu-greater-than-mapillary-greater-than-mtpw-greater-than-mtpu

This value therefore needs to be removed from API.

**Comment by good-lancer** [comment]
we need the mapillary user token to download image from mapillary.
