### ISSUE TITLE
Photographer should only be able to create one listing

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-web#129]
![a3bb1dac-4ae7-44d2-815f-27f9fb89bffb](https://user-images.githubusercontent.com/1296409/94357131-5bca2180-0096-11eb-8390-29ed4866c56e.png)

If listing exists, button should show, "edit photographer"

And when one listing exists should show has "FOR HIRE" on users profile, with link to listing (for other user).

If users own profile, if no photographer listing show "Create hire profile", if listing exists show "Edit hire profile"

![45940d3d-d47c-466f-b49e-6524245b4906](https://user-images.githubusercontent.com/1296409/94357601-91710980-009a-11eb-8c59-abeb5a65bb87.png)

**Comment by good-lancer** [comment]
if user has only one hire profile, the my photographers menu doesn't need.
So I am going to remove the tab
