### ISSUE TITLE
Challenge leaderboard not showing any results

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-web#133]
See challenge: https://map-the-paths-develop.herokuapp.com/challenge/d6ed89ba-f73e-4911-a4af-3b06a605e23e/leaderboard/?page=1&name=&transport_type=&expected_count_min=&expected_count_max=&start_time=&end_time=

No results show

But correct sequences match all challenge criteria

e.g. https://map-the-paths-develop.herokuapp.com/sequence/af498d20-fc7c-4c3f-94e8-3d3fe5284e38/detail?page=1

**Comment by good-lancer** [comment]
that works correctly
