### ISSUE TITLE
When creating label challenge, user can add their own labels

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-web#148]
User should be able to select existing MPTW tags.

They can select master (will automatically include all children -- and show this when making selection) or individual child tags

User should also be able to create new master / child tags pairs (or add child tags). This is because in some cases, tags created by admin will not meet their requirements.

https://github.com/trek-view/mtp-web/issues/49

**Comment by himynamesdave** [comment]
![download (2)](https://user-images.githubusercontent.com/1296409/94923135-a941f680-04bb-11eb-8a6a-52fd73efbac1.png)


When creating new tag full, should specify parent and child name seperatley. must user alphanumeric or - char

output will be shown like master--child

**Comment by good-lancer** [comment]
{'code': 603, 'type': 'historical_queries_not_supported_on_plan', 'info': 'Your current subscription plan does not support historical weather data. Please upgrade your account to use this
 feature.'}
