### ISSUE TITLE
Make viewpoint a button with solid green background and on right of screen

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-web#154]
![46251b0c-ca38-4086-96d3-944207ad09ce](https://user-images.githubusercontent.com/1296409/94673219-b70a4700-0316-11eb-96b1-7329cb288187.png)

Also add icon to button

[ICON] XX Viewpoints

**Comment by himynamesdave** [comment]
@good-lancer not on right, not green

**Comment by good-lancer** [comment]
Can you clear web browser cache ?
