### ISSUE TITLE
Clean up sequence sidebar for weather

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-web#161]
Currently there is a lot of data in the sidebar. 

We should include bootstrap collapsible section for weather info.

Weather (when clicked opens and shows all weather information) -- this should be below sequence elevation profile, and above image list.

![download (2)](https://user-images.githubusercontent.com/1296409/94684452-626fc780-0328-11eb-878a-dbeaa6626181.png)

**Comment by himynamesdave** [comment]
move this section below links to integrations as shown in diagram above.

also add day high and day low temperature (above sunrise / sunset)

**Comment by good-lancer** [comment]
{'code': 603, 'type': 'historical_queries_not_supported_on_plan', 'info': 'Your current subscription plan does not support historical weather data. Please upgrade your account to use this
feature.'}
