### ISSUE TITLE
clean up image directory by removing all unused images

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-web#169]
https://github.com/trek-view/mtp-web/tree/master/static/images

**Comment by himynamesdave** [comment]
and this directory @good-lancer 

https://github.com/trek-view/mtp-web/tree/master/static/images/icon

**Comment by good-lancer** [comment]
https://github.com/trek-view/mtp-web/tree/staging/static/images/icon

**Comment by good-lancer** [comment]
I'll merge when all tickets are completed.
