### ISSUE TITLE
Move /o/applications to accounts page

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-web#90]
Add "Developers" link on user profile page `/accounts/profile/`

This should link to `/accounts/applications/` and show view as currently shown on /o/applications/

/o/applications/ page should be removed

Similarly individual application pages should be put under accounts. /o/applications/2/ >>>  `/accounts/applications/2/` 

Add MTP Web styling to all `/accounts/applications/` pages

**Comment by good-lancer** [comment]
/accounts/...

**Comment by himynamesdave** [comment]
![4775e9ee-9e00-449a-b97c-ed633401ccd4](https://user-images.githubusercontent.com/1296409/93705351-cc17f680-fb1c-11ea-8b90-aed83abbb758.png)

When user logged in and on own profile page, should show button to "Developers" which links to apps page.

**Comment by himynamesdave** [comment]
closing as done
